
export const GETALL_PO_REQUEST="GETALL_PO_REQUEST"
export const GETALL_PO_SUCCESS="GETALL_PO_SUCCESS"
export const GETALL_PO_FAILURE="GETALL_PO_FAILURE"

export const GETMY_PO_REQUEST="GETMY_PO_REQUEST"
export const GETMY_PO_SUCCESS="GETMY_PO_SUCCESS"
export const GETMY_PO_FAILURE="GETMY_PO_FAILURE"


export const CREATE_PO_REQUEST="CREATE_PO_REQUEST"
export const CREATE_PO_SUCCESS="CREATE_PO_SUCCESS"
export const CREATE_PO_FAILURE="CREATE_PO_FAILURE"

export const MAKE_PAYMENT_REQUEST="MAKE_PAYMENT_REQUEST"
export const MAKE_PAYMENT_SUCCESS="MAKE_PAYMENT_SUCCESS"
export const MAKE_PAYMENT_FAILURE="MAKE_PAYMENT_FAILURE"

