export const GETALL_BATCHS_REQUEST="GETALL_BATCHS_REQUEST"
export const GETALL_BATCHS_SUCCESS="GETALL_BATCHS_SUCESS"
export const GETALL_BATCHS_FAILURE="GETALL_BATCHS_FAILURE"


export const SEARCH_BATCHS_REQUEST="SEARCH_BATCHS_REQUEST"
export const SEARCH_BATCHS_SUCCESS="SEARCH_BATCHS_SUCESS"
export const SEARCH_BATCHS_FAILURE="SEARCH_BATCHS_FAILURE"

export const GETMY_BATCHS_REQUEST="GETMY_BATCHS_REQUEST"
export const GETMY_BATCHS_SUCCESS="GETMY_BATCHS_SUCESS"
export const GETMY_BATCHS_FAILURE="GETMY_BATCHS_FAILURE"


export const LECTURER_GETMY_BATCHS_REQUEST="LECTURER_GETMY_BATCHS_REQUEST"
export const LECTURER_GETMY_BATCHS_SUCCESS="LECTURER_GETMY_BATCHS_SUCESS"
export const LECTURER_GETMY_BATCHS_FAILURE="LECTURER_GETMY_BATCHS_FAILURE"


export const SUBJECTS_REQUEST="SUBJECTS_REQUEST"
export const SUBJECTS_SUCCESS="SUBJECTS_SUCCESS"
export const SUBJECTS_FAILURE="SUBJECTS_FAILURE"

export const GET_COURSES_REQUEST="GET_COURSES_REQUEST"
export const GET_COURSES_SUCCESS="GET_COURSES_SUCCESS"
export const GET_COURSES_FAILURE="GET_COURSES_FAILURE"