

export const CREATE_BATCH_REQUEST="CREATE_BATCH_REQUEST"
export const CREATE_BATCH_SUCCESS="CREATE_BATCH_SUCCESS"
export const CREATE_BATCH_FAILURE="CREATE_BATCH_FAILURE"

export const CREATE_COURSE_REQUEST="CREATE_COURSE_REQUEST"
export const CREATE_COURSE_SUCCESS="CREATE_COURSE_SUCCESS"
export const CREATE_COURSE_FAILURE="CREATE_COURSE_FAILURE"

export const CREATE_SUBJECT_REQUEST="CREATE_SUBJECT_REQUEST"
export const CREATE_SUBJECT_SUCCESS="CREATE_SUBJECT_SUCCESS"
export const CREATE_SUBJECT_FAILURE="CREATE_SUBJECT_FAILURE"

export const CREATE_LECTURER_REQUEST="CREATE_LECTURER_REQUEST"
export const CREATE_LECTURER_SUCCESS="CREATE_LECTURER_SUCCESS"
export const CREATE_LECTURER_FAILURE="CREATE_LECTURER_FAILURE"

export const ASSIGN_REQUEST="ASSIGN_REQUEST"
export const ASSIGN_SUCCESS="ASSIGN_SUCCESS"
export const ASSIGN_FAILURE="ASSIGN_FAILURE"
