
export const CREATECLASS_REQUEST="CREATECLASS_REQUEST"
export const CREATECLASS_SUCCESS="CREATECLASS_SUCCESS"
export const CREATECLASS_FAILURE="CREATECLASS_FAILURE"

export const CREATECLASSROOM_REQUEST="CREATECLASSROOM_REQUEST"
export const CREATECLASSROOM_SUCCESS="CREATECLASSROOM_SUCCESS"
export const CREATECLASSROOM_FAILURE="CREATECLASSROOM_FAILURE"

export const UPLOAD_VIDEO_REQUEST="UPLOAD_VIDEO_REQUEST"
export const UPLOAD_VIDEO_SUCCESS="UPLOAD_VIDEO_SUCCESS"
export const UPLOAD_VIDEO_FAILURE="UPLOAD_VIDEO_FAILURE"

export const UPLOAD_NOTES_REQUEST="UPLOAD_NOTES_REQUEST"
export const UPLOAD_NOTES_SUCCESS="UPLOAD_NOTES_SUCCESS"
export const UPLOAD_NOTES_FAILURE="UPLOAD_NOTES_FAILURE"

export const CREATE_TEST_REQUEST="CREATE_TEST_REQUEST"
export const CREATE_TEST_SUCCESS="CREATE_TEST_SUCCESS"
export const CREATE_TEST_FAILURE="CREATE_TEST_FAILURE"

export const SUBMIT_TEST_REQUEST="SUBMIT_TEST_REQUEST"
export const SUBMIT_TEST_SUCCESS="SUBMIT_TEST_SUCCESS"
export const SUBMIT_TEST_FAILURE="SUBMIT_TEST_FAILURE"

export const LECTURER_PROGRESS_SET="LECTURER_PROGRESS_SET"
export const LECTURER_PROGRESS_RESET="LECTURER_PROGRESS_RESET"
